[package]
name = "day-19-clap"
version = "0.1.0"
edition = "2024"

[dependencies]
camino = "1.2.2"
clap = { version = "4.5.56", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
slug = "0.1.6"
