[package]
name = "day-23-garden"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["env", "derive"] }
dialoguer = "0.12.0"
directories = "6.0.0"
edit = "0.1.5"
owo-colors = "4.2.3"
slug = "0.1.6"
